sudo: required
dist: trusty

language: haxe

haxe:
 - "3.4.7"
 - "4.1.3"
 
hxml:
 - test/ImportAll.hxml

install:
 - haxelib install test/ImportAll.hxml --always --quiet
 - haxelib install starling-text-display --always --quiet
 - haxelib dev starling-text-display . --quiet
 - haxelib run lime setup -y --quiet
 
script:
 - lime build test/ImportAll.lime html5
 
deploy:
 - provider: script
   haxe: 3.4.7
   script: bash ./release_haxelib.sh $HAXELIB_PWD